Adds impl FromSkyhashBytes for RawString and a TODO
skytable/client-rust pull request #16
Opened 2022-12-22 20:13 UTC by emchristiansen

This is just a code sketch, as I'm a bit unclear on a couple things:

1. I'm not sure why this wasn't already included (and I assume you have a good reason).
1. I don't understand why you're encoding the key / value data the way you are. For example, in line 475 you seem to assume primitives are encoded as UTF8 strings, which seems very odd. Rather I'd expect everything in the DB to be (arbitrary, not UTF8) `Vec<u8>`s. I think you can convert all these primitives to bytes using functions like `_.to_le_bytes()`.

Relatedly, I'm not sure why you need the `RawString` type instead of just implementing the appropriate traits for `Vec<u8>`.

2022-12-22 20:13 UTC, glydr commented
[![CLA assistant check](https://cla.skytable.io/pull/badge/not_signed)](https://cla.skytable.io/skytable/client-rust?pullRequest=16) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.skytable.io/skytable/client-rust?pullRequest=16) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.skytable.io/check/skytable/client-rust?pullRequest=16) it.</sub>

2022-12-23 05:42 UTC, ohsayan requested changes

2022-12-23 05:42 UTC, ohsayan commented on src/types.rs
> +                    // TODO: Represent primitives more efficiently.
This is just for convenience. We can simply do a `to_string` but it's not applicable for other types in this specific shorthand. Second, no, primitive types are **not** represented as strings internally. The formatting infrastructure is used to produce strings for types like integers.

2022-12-23 05:44 UTC, ohsayan requested changes

2022-12-23 05:44 UTC, ohsayan commented on src/types.rs
> +
`RawString` is simply a wrapper around `Vec<u8>` and only makes sense for sending queries that contain binary data and not reading them. Is there any specific reason you want to parse into a `RawString` and not a `Vec<u8>`?

2022-12-23 05:52 UTC, ohsayan commented
> I don't understand why you're encoding the key / value data the way you are. For example, in line 475 you seem to assume primitives are encoded as UTF8 strings,

The `FromSkyhashBytes` trait is more of an application layer parsing impl than anything related to how Skytable itself stores data. It is provided for convenience. Since currently the database allows storing a string/binary as a key/value and permutations of the same, you might have done something like this in your application code:

```rust
db.set("myint", "100").unwrap();
```

Now let's say your table stores: `string` key -> `binary` value. If you did a parse into the actual protocol level type, you'd run this:

```rust
let protocol_element: Element = db.get("myint").unwrap();
```

This would give you `Element::Binary`, but you actually wanted an integer. This is why the `FromSkyhashBytes` trait exists to make it convenient for you to simply run this:

```rust
let myint: u8 = db.get("myint").unwrap();
```

I hope this clears things up a bit :)

2023-01-02 13:25 UTC, closed without merging